spring.application.name=api-gateway
server.port=8080

# Redis for rate limiting
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT
jwt.secret=payflow-super-secret-key-for-hmac-sha-256-algorithm-minimum-32-bytes-long-enough

# Service URLs
user-service.url=http://localhost:8081
account-service.url=http://localhost:8082
transaction-service.url=http://localhost:8083
notification-service.url=http://localhost:8085

# Logging
logging.level.org.springframework.cloud.gateway=INFO
