spring.application.name=account-service
server.port=8082

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/accounts_db
spring.datasource.username=root
spring.datasource.password=payflow123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
jwt.secret=payflow-super-secret-key-for-hmac-sha-256-algorithm-minimum-32-bytes-long-enough

# User Service URL
user-service.url=http://localhost:8081
